coerce string returned from string-downcase to runes:simple-rod
sharplispers/cxml-stp pull request #1
Opened 2018-10-24 16:52 UTC by slyrus

* This relates to the issue discuseed here:
   <https://github.com/sharplispers/closure-common/pull/4>. If we
   don't change the runes:simple-rod type to admit simple-base-string
   then we run into a problem when we try to pass a simple-base-string
   on to CXML. So, if we're not gonig to change the type of
   simple-rod, we need to coerce the string returned from
   string-downcase to a simple-rod.

2018-10-29 08:46 UTC, scymtym requested changes
The actual change and rationale LGTM, but while at it, you could also change `(string-downcase (princ-to-string (symbol-name …)))` to just `(string-downcase …)`, so `(coerce (string-downcase entry) 'runes:simple-rod)`.

2019-04-06 21:13 UTC, slyrus commented
Ok, it took a while but I've made the requested change.

2019-04-06 22:05 UTC, metayan commented
With SBCL, `(ql:quickload :xpath)` causes the heap to be exhausted, due to the dependency on xpath/test . (Can be solved with `sbcl --dynamic-space-size 1500`.)
However, if
```lisp
(defun run-xpath-tests ()
  (let ((xpath-test:*dom-builder* (stp:make-builder))
        (xpath-test:*document-element* #'stp:document-element))
    (xpath-test::run-all-tests)))
```
is moved from `xpath.lisp` to `test.lisp`, the `:xpath/test` dependency can be removed from `cxml-stp.asd`. This also allows `xpath` to load much faster.

2019-04-09 08:16 UTC, scymtym commented
@slyrus I slightly adjusted the commit messages to match the style used by David.

@metayan Is your remark for this pull request? It seems unrelated. But yes, I was also thinking about not loading `xpath/test` all the time.

2019-04-09 08:16 UTC, closed without merging

2019-04-09 11:48 UTC, metayan commented
@scymtym You're right, those issues are not related to this PR.